apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
      - name: springboot-app
        image: jpalaparthi/toledo-cruddemo
        env:
        - name: DB_HOST
          value: postgresql.default.svc.cluster.local
          # <service-name>.<namespace>.svc.cluster.local
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: springboot_crud
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          value: postgres
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-app
spec:
  selector:
    app: springboot-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

