apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  DB_HOST: postgresql.default.svc.cluster.local
  DB_PORT: "5432"
  DB_NAME: springboot_crud
  DB_USER: postgres
  DB_PASSWORD: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  DB_USER: postgres
  DB_PASSWORD: postgres

